name: RedNine
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90791
title: Brisbane Commercial Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#da3d1c'
    - '#9f9f9f'
    - '#d63b1d'
    - '#a69fa3'
  brandStrength: 0.8651528155896813
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.3795643295161426
purpose: []
