name: RedNine
favicon: null
layout_spectrum: 0.33229
typography_spectrum: 0.05563341802917421
title: Brisbane Commercial Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8651528155896813
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.3795643295161426
purpose: []
